blank_issues_enabled: false
contact_links:
  - name: 🗨 Discord
    url: https://discord.gg/N55gSQcVEC
    about: Do you have any other questions? Join our Discord server and ask us in the tech support channel!